apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ovjstoux
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-ovjstoux:9b13f90a99fab2485ad14dc8bea601bbd6e993da@sha256:6ca10eafa53ef90c842b7d01f830e56d2026566303b1af85e0057be300be04bb
        name: container-image  
